-- INSERT INTO bike  (name,description,price,mark,color,bike_type,bike_code) VALUES  ('FirstBike','To jest pierwszy rower',5000,'KANDS','niebieski','CROSS','23232D'),
--                                                                                   ('SecondBike','To jest drugi rower',5000,'KANDS','niebieski','CROSS','23232D'),
--                                                                                   ('ThirdBike','To jest trzeci rower',5000,'KANDS','niebieski','CROSS','23232D');
-- INSERT INTO bottles (name,price,product_code,weight,capacity,material,thermal,accessories_type,color,description,mark) VALUES
-- ('ButelkaTest',100,'23132DE',10,3,'plastik',true,'BOTTLE','czerwony','butelka do picia wody','KANDS');
--
-- INSERT INTO pump (name, is_catridge, manometer) VALUES ('Pompeczka testowa',false,true);
--
-- INSERT INTO maintenance (name) VALUES ('Olej');
--
-- INSERT INTO racks (name) VALUES ('Olej');
--
-- INSERT INTO tools (name) VALUES ('Olej');
--
-- INSERT INTO brake (name) VALUES ('Shimano hamulec');
--
-- INSERT INTO drive (name) VALUES ('Silnnik testowy');
--
-- INSERT INTO frame (name) VALUES ('Rama testowa');

select * from bike;
